<div class="art_collection-group">
    <div>
        <div class="form-group">
            <div class="col-sm-1" style="padding-left: 0px;width: 70px;">
                <?php echo $this->getExtension('input', array(
                            'name' => 'city['.(isset($this->city['id']) != '' ? $this->city['id'] : '__counter__').'][id]',
                            'value' => $this->city['id'],
                            'placeholder' => 'ID',
                            'attr' => array('readonly')
                        )
                    ); 
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3" style="padding-left: 0px;">
                <?php echo $this->getExtension('input', array(
                            'name' => 'city['.(isset($this->city['id']) != '' ? $this->city['id'] : '__counter__').'][name]',
                            'value' => $this->city['name'],
                            'placeholder' => 'Название'
                        )
                    ); 
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3" style="padding-left: 0px;">
                <?php echo $this->getExtension('input', array(
                            'name' => 'city['.(isset($this->city['id']) != '' ? $this->city['id'] : '__counter__').'][alias]',
                            'value' => $this->city['alias'],
                            'placeholder' => 'Псевдоним'
                        )
                    ); 
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-1" style="margin-left: -25px;width: 150px;">
                <?php echo $this->getExtension('switch', array(
                            'name' => 'city['.(isset($this->city['id']) != '' ? $this->city['id'] : '__counter__').'][default_city]',
                            'value' => $this->city['default_city'],
                            'placeholder' => 'Цены по умолчанию'
                        )
                    ); 
                ?>
            </div>
        </div>
        <a href="<?php echo $this->factory('router')->generate('Settings', 'removeCity'); ?>" data="<?php echo $this->city['id']; ?>" class="btn btn-danger js_art_remove-collection" style="margin-bottom: 5px;"><span class="glyphicon glyphicon-trash"></span> Удалить город</a>
    </div>
</div>