<div class="form-group">
    <label class="col-sm-2 control-label">Имя:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'name',
                    'value' => $this->letter['name']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Подпись:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'subject',
                    'value' => $this->letter['subject']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Дата создания:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('datetime', array(
                    'name' => 'created_at',
                    'value' => $this->letter['created_at']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Тип:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->factory('config')->loadConfigFile('mailer')->getNode('letter_type/item')->nodeToArray(), 
                    'required' => true, 
                    'name' => 'type',
                    'selected' => $this->letter['type']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Сообщение:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('textarea', array(
                    'name' => 'text',
                    'editor' => false,
                    'attr' => array('rows' => 5),
                    'value' => $this->letter['text']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Id Чанка:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'chunk_id',
                    'value' => $this->letter['chunk_id']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Id Ресурса:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'resource_id',
                    'value' => $this->letter['resource_id']
                )
            ); 
        ?>
    </div>
</div>