<div id="art_breadcrumb">
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->factory('router')->generate('Main', 'index'); ?>">Главная</a></li>
        <li class="active">Данные городов</li>
    </ul>
</div>

<div id="art_actionbar">
    <button type="button" class="btn btn-success js_submitForm"><span class="glyphicon glyphicon-ok"></span> Обновить</button>
    <button type="button" class="btn art_actionbar-scroll-top"><span class="glyphicon glyphicon-arrow-up"></span></button>
</div>

<ul class="nav nav-tabs" id="art_content-tab-navigation-nojs">
    <li><a href="<?php echo $this->factory('router')->generate('Settings', 'size'); ?>">Размеры</a></li>
    <li class="active"><a href="<?php echo $this->factory('router')->generate('Settings', 'city'); ?>">Города</a></li>
</ul>

<div class="art_help_block text-muted">
    
</div>

<form action="<?php echo $this->factory('router')->generate('Settings', 'cityUpdate'); ?>" method="post" class="art_data-grid-form">
    <input type="hidden" name="product_id" value="1">
    <div id="art_content-tab-content" class="tab-content">
        <div class="tab-pane active" id="city">
            <a class="btn btn-success js_art_add-collection" style="margin-bottom: 5px;" data-content="<?php echo htmlspecialchars($this->display('Settings/City/city')) ; ?>"><span class="glyphicon glyphicon-plus"></span> Добавить город</a>
            <?php if ($this->citys != null && count($this->citys) > 0): ?>
                <?php foreach ($this->citys as $key => $value): ?>
                    <?php echo $this->display('Settings/City/city', array('city' => $value)) ; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
</form>
