<div class="form-group">
    <label class="col-sm-2 control-label">Имя:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'name',
                    'value' => $this->review['name']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Email:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'email',
                    'value' => $this->review['email']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Дата создания:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('datetime', array(
                    'name' => 'created_at',
                    'value' => $this->review['created_at']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Статус:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->factory('config')->loadConfigFile('review')->getNode('status/item')->nodeToArray(), 
                    'required' => true, 
                    'name' => 'status',
                    'selected' => $this->review['status']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Пользователь:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->users, 
                    'required' => false, 
                    'search' => true,
                    'name' => 'user_id',
                    'selected' => $this->review['user_id'],
                    'label_name' => 'fullname',
                    'value_name' => 'internalKey'
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Товар:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('select', array(
                    'array'=>$this->products, 
                    'required' => false, 
                    'name' => 'product_id',
                    'selected' => $this->review['product_id'],
                    'label_name' => 'name',
                    'value_name' => 'id'
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Сообщение:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('textarea', array(
                    'name' => 'message',
                    'editor' => false,
                    'attr' => array('rows' => 5),
                    'value' => $this->review['message']
                )
            ); 
        ?>
    </div>
</div>