<div id="art_breadcrumb">
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->factory('router')->generate('Main', 'index'); ?>">Главная</a></li>
        <li><a href="<?php echo $this->factory('router')->generate('Mailer', 'indexLetter'); ?>">Все шаблоны</a></li>
        <li class="active">Редактирование шаблона</li>
    </ul>
</div>

<div id="art_actionbar">
    <a href="<?php echo CRM_GET_REFERER_URL(); ?>" class="btn btn-danger"><span class="glyphicon glyphicon-arrow-left"></span> Назад</a>
    <button type="button" class="btn btn-success js_submitForm"><span class="glyphicon glyphicon-ok"></span> Обновить</button>
    <button type="button" class="btn art_actionbar-scroll-top"><span class="glyphicon glyphicon-arrow-up"></span></button>
</div>

<ul class="nav nav-tabs" id="art_content-tab-navigation">
    <li class="active"><a href="#letter">Информация</a></li>
    <li class="art_help-block"><span class="text-muted">ID - <?php echo $this->letter['id']; ?></span></li>
</ul>

<form action="<?php echo $this->factory('router')->generate('Mailer', 'editLetter', array('letter_id' => $this->letter['id'])); ?>" method="POST" enctype="multipart/form-data" class="form-horizontal art_data-grid-form">
    <div id="art_content-tab-content" class="tab-content">
        <div class="tab-pane active" id="letter">
            <?php echo $this->display('Mailer/Letter/letter_tab', array('letter' => $this->letter)) ; ?>
        </div>
    </div>
</form>