<?php if ($this->factory('flesh')->isFlesh()): ?>
    <?php foreach ($this->factory('flesh')->getFlesh() as $key => $value): ?>
        <div class="alert alert-<?php echo $value['color']; ?> art_flash-alert"  style="display:block !important" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button>
            <strong><?php echo $value['alert']; ?></strong>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
