<div class="form-group">
    <label class="col-sm-2 control-label">Имя:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'name',
                    'value' => $this->filter['name']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Позиция:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('touchspin', array(
                    'name' => 'position',
                    'value' => $this->filter['position']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Дата создания:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('datetime', array(
                    'name' => 'created_at',
                    'value' => $this->filter['created_at']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Тип:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->factory('config')->loadConfigFile('filter')->getNode('type/item')->nodeToArray(), 
                    'required' => true, 
                    'name' => 'type',
                    'selected' => $this->filter['type']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Категории:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->categorys, 
                    'required' => true, 
                    'name' => 'categorys[]',
                    'attr' => array('multiple'),
                    'selected' => $this->selected_categorys,
                    'label_name' => 'pagetitle,catalog_name',
                    'value_name' => 'id'
                )
            ); 
        ?>
    </div>
</div>