<head>
    <meta charset="UTF-8" />
    <title><?php echo $this->factory('config')->getVal('app', 'site_name', 'application') ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    
    <link href="<?php echo MMP; ?>assets/css/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/bootstrap-select.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/bootstrap-switch.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/bootstrap-datetimepicker.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/elusive-webfont.css" type="text/css" rel="stylesheet" /><!--http://shoestrap.org/downloads/elusive-icons-webfont/-->
    <link href="<?php echo MMP; ?>assets/css/font-awesome.min.css" type="text/css" rel="stylesheet" /><!--http://fortawesome.github.io/Font-Awesome/-->
    <link href="<?php echo MMP; ?>assets/css/bootstrap-theme.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/bootstrap-touchspin.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/summernote.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/bootstrap-editable.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/mm-autocomplete.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo MMP; ?>assets/css/main.css" type="text/css" rel="stylesheet" />

    <script src="<?php echo MMP; ?>assets/js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/bootstrap-select.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/bootstrap-switch.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/moment.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/bootstrap-datetimepicker.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/bootstrap-datetimepicker.ru.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/bootstrap-touchspin.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/summernote.min.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/bootstrap-editable.min.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/flot/jquery.flot.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/flot/jquery.flot.pie.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/flot/jquery.flot.categories.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/flot/jquery.flot.selection.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/mm-autocomplete.js" type="text/javascript"></script>
    <script src="<?php echo MMP; ?>assets/js/main.js?v=1" type="text/javascript"></script>
</head>