<div id="art_breadcrumb">
    <ul class="breadcrumb">
        <li><a href="<?php echo $this->factory('router')->generate('Main', 'index'); ?>">Главная</a></li>
        <li><a href="<?php echo $this->factory('router')->generate('Filter', 'index'); ?>">Все фильтры</a></li>
        <li class="active">Редактирование фильтра</li>
    </ul>
</div>

<div id="art_actionbar">
    <a href="<?php echo CRM_GET_REFERER_URL(); ?>" class="btn btn-danger"><span class="glyphicon glyphicon-arrow-left"></span> Назад</a>
    <button type="button" class="btn btn-success js_submitForm"><span class="glyphicon glyphicon-ok"></span> Обновить</button>
    <button type="button" class="btn art_actionbar-scroll-top"><span class="glyphicon glyphicon-arrow-up"></span></button>
</div>

<ul class="nav nav-tabs" id="art_content-tab-navigation">
    <li class="active"><a href="#filter">Информация</a></li>
    <li><a href="#value">Значения фильтра</a></li>
    <li class="art_help-block"><span class="text-muted">ID - <?php echo $this->filter['id']; ?></span></li>
</ul>

<form action="<?php echo $this->factory('router')->generate('Filter', 'edit', array('filter_id' => $this->filter['id'])); ?>" method="POST" enctype="multipart/form-data" class="form-horizontal art_data-grid-form">
    <div id="art_content-tab-content" class="tab-content">
        <div class="tab-pane active" id="filter">
            <?php echo $this->display('Filter/filter_tab', array('filter' => $this->filter)) ; ?>
        </div>
        <div class="tab-pane" id="value">
            <?php echo $this->display('Filter/Value/filter_value_tab') ; ?>
        </div>
    </div>
</form>