<div class="form-group">
    <label class="col-sm-2 control-label">Имя:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'name',
                    'value' => $this->subscriber['name']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Email:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('input', array(
                    'name' => 'email',
                    'value' => $this->subscriber['email']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Дата создания:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('datetime', array(
                    'name' => 'created_at',
                    'value' => $this->subscriber['created_at']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Статус:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->factory('config')->loadConfigFile('mailer')->getNode('subscriber_status/item')->nodeToArray(), 
                    'required' => true, 
                    'name' => 'status',
                    'selected' => $this->subscriber['status']
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Шаблоны:</label>
    <div class="col-sm-3">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->letters, 
                    'required' => true, 
                    'name' => 'letters[]',
                    'attr' => array('multiple'),
                    'selected' => $this->selected_letters,
                    'label_name' => 'name',
                    'value_name' => 'id'
                )
            ); 
        ?>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Пользователь:</label>
    <div class="col-sm-2">
        <?php echo $this->getExtension('selectpicker', array(
                    'array'=>$this->users, 
                    'required' => false, 
                    'search' => true,
                    'name' => 'user_id',
                    'selected' => $this->subscriber['user_id'],
                    'label_name' => 'fullname',
                    'value_name' => 'internalKey'
                )
            ); 
        ?>
    </div>
</div>