<?php if(!in_array($this->filter['id'], array(14))):?>
<a class="btn btn-success js_art_add-collection" style="margin-bottom: 5px;" data-content="<?php echo htmlspecialchars($this->display('Filter/Value/filter_value', array('value' => ''))) ; ?>"><span class="glyphicon glyphicon-plus"></span> Добавить значение</a>
<?php endif; ?>
<?php if ($this->filter_values != null && count($this->filter_values) > 0): ?>
    <?php foreach ($this->filter_values as $key => $value): ?>
        <?php echo $this->display('Filter/Value/filter_value', array('row' => $value)) ; ?>
    <?php endforeach; ?>
<?php endif; ?>