<div class="art_collection-group">
    <div>
        <div class="form-group">
            <div class="col-sm-8">
                <?php echo $this->getExtension('select', array(
                            'array'=> $this->citys, 
                            'name' => 'size['.(isset($this->size['id']) != '' ? $this->size['id'] : '__counter__').'][citys]['.(isset($this->city['id']) != '' ? $this->city['id'] : '__counter__').'][city_id]',
                            'selected' => $this->city['city_id'],
                            'label_name' => 'name',
                            'value_name' => 'id'
                        )
                    ); 
                ?>
            </div>
            <div class="col-sm-4">
                <a href="<?php echo $this->factory('router')->generate('Product', 'removeSizeCity'); ?>" data="<?php echo $this->city['id'];?>" class="btn btn-danger js_art_remove-collection" style="margin-bottom: 5px;"><span class="glyphicon glyphicon-trash"></span> Удалить</a>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-6">
                <?php echo $this->getExtension('input', array(
                            'name' => 'size['.(isset($this->size['id']) != '' ? $this->size['id'] : '__counter__').'][citys]['.(isset($this->city['id']) != '' ? $this->city['id'] : '__counter__').'][price]',
                            'value' => $this->city['price'],
                            'placeholder' => 'Цена'
                        )
                    ); 
                ?>
            </div>
            <div class="col-sm-6">
                <?php echo $this->getExtension('input', array(
                            'name' => 'size['.(isset($this->size['id']) != '' ? $this->size['id'] : '__counter__').'][citys]['.(isset($this->city['id']) != '' ? $this->city['id'] : '__counter__').'][sale_price]',
                            'value' => $this->city['sale_price'],
                            'placeholder' => 'Акционная цена'
                        )
                    ); 
                ?>
            </div>
        </div>
    </div>
    <hr style="margin-top: 5px;margin-bottom: 5px;">
</div>