<div class="art_collection-group">
    <div>
        <div class="form-group">
            <div class="col-sm-1" style="padding-left: 0px;width: 70px;">
                <?php echo $this->getExtension('input', array(
                            'name' => 'size['.(isset($this->size['value']) != '' ? $this->size['value'] : '__counter__').'][value]',
                            'value' => $this->size['value'],
                            'placeholder' => 'ID',
                            'attr' => array('readonly')
                        )
                    ); 
                ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3" style="padding-left: 0px;">
                <?php echo $this->getExtension('input', array(
                            'name' => 'size['.(isset($this->size['value']) != '' ? $this->size['value'] : '__counter__').'][size]',
                            'value' => $this->size['label'],
                            'placeholder' => 'Размер'
                        )
                    ); 
                ?>
            </div>
        </div>
        <a href="<?php echo $this->factory('router')->generate('Settings', 'removeSize'); ?>" data="<?php echo $this->size['value']; ?>" class="btn btn-danger js_art_remove-collection" style="margin-bottom: 5px;"><span class="glyphicon glyphicon-trash"></span> Удалить размер</a>
    </div>
</div>